apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: 180169423799.dkr.ecr.us-east-1.amazonaws.com/demo-project:master-4ea81a0b4031f793e5e22f60672641bce15c2fec
          ports:
            - containerPort: 8080
