apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: 063738659414.dkr.ecr.ap-south-1.amazonaws.com/nodejs-project:master-0e95fd31f8e2998ea2facde4e47c50324db4ef12
          ports:
            - containerPort: 8080
